### ISSUE TITLE
I think I have found an issue

### ISSUE THREAD

**Issue by cpu-cpu** [89pleasure/cities2-mod-collection#1]
In every csproj file you have published there is 
```
<Cities2_Location>E:\SteamLibrary\steamapps\common\Cities Skylines II</Cities2_Location>
```
Well the thing is, me and probably a lot of other people use the C drive to store cities skylines 2. I'm not sure if this matters, but I just wanted to point it out.

**Comment by 89pleasure** [comment]
This is intended. It's a config variable you need to change if you compile the source by yourself and point to your game location.
